# Generated by Django 4.2.6 on 2023-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agantapp', '0002_alter_agant_uniprotid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDB', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=255)),
                ('Response', models.CharField(max_length=255)),
                ('Ligand', models.CharField(max_length=255)),
                ('Uniprot_accession', models.CharField(max_length=255)),
                ('Lig_vol', models.FloatField()),
                ('Pock_vol', models.FloatField()),
                ('DrugScore', models.FloatField()),
                ('Average_B_Factor', models.FloatField()),
                ('All_atoms_rsa_cavity', models.FloatField()),
                ('Predicted_Average_pKd', models.FloatField()),
                ('Total_Surface_Area', models.FloatField()),
            ],
        ),
    ]
