# Generated by Django 4.2.7 on 2023-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agantapp', '0003_proteindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteindata',
            name='All_atoms_rsa_cavity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='Average_B_Factor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='DrugScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='Lig_vol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='Pock_vol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='Predicted_Average_pKd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='Total_Surface_Area',
            field=models.FloatField(null=True),
        ),
    ]
